/*
 * tcp_sans_io.h — C header for the tcp-sans-io stack.
 *
 * Generated by hand from src/ffi.rs. ABI version is queryable at runtime via
 * `tcp_abi_version()`; bump it on any breaking change.
 */
#ifndef TCP_SANS_IO_H
#define TCP_SANS_IO_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- States (matches Rust enum State, repr(u8)) ----------------------- */
#define TCP_STATE_CLOSED       0
#define TCP_STATE_SYN_SENT     1
#define TCP_STATE_ESTABLISHED  2
#define TCP_STATE_FIN_WAIT_1   3
#define TCP_STATE_FIN_WAIT_2   4
#define TCP_STATE_CLOSING      5
#define TCP_STATE_TIME_WAIT    6
#define TCP_STATE_CLOSE_WAIT   7
#define TCP_STATE_LAST_ACK     8
#define TCP_STATE_LISTEN       9
#define TCP_STATE_SYN_RCVD     10
#define TCP_STATE_INVALID      0xFF

/* ---- Errors (negative) ------------------------------------------------- */
#define TCP_ERR_BUFFER_TOO_SMALL  (-1)
#define TCP_ERR_NULL_POINTER      (-2)
#define TCP_ERR_INVALID_STATE     (-3)
#define TCP_ERR_MALFORMED_PACKET  (-4)
#define TCP_ERR_NOT_FOR_US        (-5)
#define TCP_ERR_WOULD_BLOCK       (-6)
#define TCP_ERR_CONNECTION_RESET  (-7)
#define TCP_ERR_CONNECTION_CLOSED (-8)
#define TCP_ERR_OVERFLOW          (-9)

/* ---- Event flags returned by tcp_poll --------------------------------- */
#define TCP_EV_READABLE     (1u << 0)
#define TCP_EV_WRITABLE     (1u << 1)
#define TCP_EV_ESTABLISHED  (1u << 2)
#define TCP_EV_PEER_CLOSED  (1u << 3)
#define TCP_EV_CLOSED       (1u << 4)
#define TCP_EV_TX_PENDING   (1u << 5)
#define TCP_EV_ERROR        (1u << 6)
#define TCP_EV_LISTENING    (1u << 7)
#define TCP_EV_HALF_OPEN    (1u << 8)

/* ---- Opaque handle ----------------------------------------------------- */
typedef struct TcpStreamHandle TcpStreamHandle;

/* ---- ABI / sizing ------------------------------------------------------ */
uint32_t tcp_abi_version(void);
size_t   tcp_handle_size(void);
size_t   tcp_handle_align(void);
/* Maximum byte size of a single IPv4+TCP datagram the stack can emit.
 * Hosts use this to size their per-TCB extract_packet scratch buffer.
 * Currently 1500 (IPv4 fixed 20 + TCP fixed 20 + MSS 1460). */
size_t   tcp_max_packet(void);

/* Built-in self-conformance smoke test. Drives two in-process instances of
 * the stack through a byte-exact bidirectional bulk transfer and a clean
 * close — no storage, transport, clock, or reference peer required. Returns
 * 0 on success or a negative stage code (see crate::selftest::result).
 * Call once after loading the library to confirm linkage / ABI / calling
 * convention before wiring up a real connection. Uses ~256 KiB of the
 * caller's stack for well under a millisecond. */
int32_t  tcp_selftest(void);

/* ---- Lifecycle --------------------------------------------------------- */
int32_t tcp_init(TcpStreamHandle* storage,
                 const uint8_t* local_ip,  uint16_t local_port,
                 const uint8_t* remote_ip, uint16_t remote_port,
                 uint32_t iss, uint32_t initial_rto_ms);
int32_t tcp_destroy(TcpStreamHandle* handle);

/* ---- Connection control ----------------------------------------------- */
int32_t tcp_connect(TcpStreamHandle* handle, uint64_t now_ms);
int32_t tcp_listen (TcpStreamHandle* handle, uint64_t now_ms);
int32_t tcp_close  (TcpStreamHandle* handle, uint64_t now_ms);
/* Abort the connection: queues a TCP RST+ACK in the TX ring, transitions
 * the handle to CLOSED, drops all buffered send/recv/OOO bytes, and
 * surfaces ConnectionReset via tcp_poll()'s ERROR flag. After calling
 * this, drain the TX ring once with tcp_extract_packet to emit the RST,
 * then call tcp_destroy. Idempotent on CLOSED; no wire effect in
 * LISTEN/SYN_SENT. */
int32_t tcp_abort  (TcpStreamHandle* handle, uint64_t now_ms);
int32_t tcp_tick   (TcpStreamHandle* handle, uint64_t now_ms);

/* Install a 16-byte secret enabling stateless SYN cookies (RFC 4987).
 * `secret` must point to exactly 16 readable bytes from a CSPRNG. */
int32_t tcp_set_cookie_secret(TcpStreamHandle* handle, const uint8_t* secret);

/* Reconfigure/disable TCP keepalive (RFC 9293 3.8.4). After `idle_ms` of
 * inbound silence on an idle ESTABLISHED connection (nothing in flight), up
 * to `count` probes are sent `intvl_ms` apart; if none is answered the
 * connection aborts as a vanished peer (ConnectionReset via tcp_poll ERROR /
 * tcp_recv), no RST emitted. Any inbound segment resets the idle timer.
 * ON BY DEFAULT (10 min idle / 60 s interval / 4 probes ~= 14 min to reap),
 * so an abandoned idle connection cannot pin its buffers forever; pass
 * `idle_ms == 0` to disable. */
int32_t tcp_set_keepalive(TcpStreamHandle* handle, uint64_t now_ms,
                          uint32_t idle_ms, uint32_t intvl_ms, uint8_t count);

/* Set the RFC 9293 3.8.3 USER TIMEOUT: max time the connection may go without
 * forward progress (snd_una advancing) while it still has unacknowledged send
 * data, before it aborts (ConnectionReset via tcp_poll ERROR / tcp_recv, no
 * RST). ON BY DEFAULT (5 min) — bounds the zero-window / dribbled-ACK DoS (an
 * alive-but-stalling peer answering probes while never opening its window).
 * Resets only on real progress, so it is immune to that proof-of-life trick.
 * `user_timeout_ms == 0` disables it. */
int32_t tcp_set_user_timeout(TcpStreamHandle* handle, uint64_t now_ms,
                             uint32_t user_timeout_ms);

/* ---- State / polling --------------------------------------------------- */
uint8_t  tcp_state(const TcpStreamHandle* handle);
uint32_t tcp_poll (const TcpStreamHandle* handle);

/* ---- App ⇄ TCP buffers ------------------------------------------------- */
int32_t tcp_send(TcpStreamHandle* handle,
                 const uint8_t* data, size_t len, size_t* out_written);
int32_t tcp_recv(TcpStreamHandle* handle,
                 uint8_t* buf, size_t cap, size_t* out_read);

/* ---- TCP ⇄ WireGuard datagrams ---------------------------------------- */
int32_t tcp_inject_packet (TcpStreamHandle* handle,
                           const uint8_t* packet, size_t len, uint64_t now_ms);
int32_t tcp_extract_packet(TcpStreamHandle* handle,
                           uint8_t* buf, size_t cap, size_t* out_written);

/* ---- Diagnostics (NOT a stable ABI) ----------------------------------- */
typedef struct TcpDebugSnapshot {
    uint32_t snd_una;
    uint32_t snd_nxt;
    uint32_t snd_wnd;
    uint32_t rcv_nxt;
    uint32_t cwnd;
    uint32_t ssthresh;
    uint32_t rto_ms;
    uint64_t rto_deadline;
    uint64_t now_ms;
    uint32_t send_ring_len;
    uint32_t recv_ring_len;
    uint32_t oo_start;
    uint32_t oo_len;
    uint32_t tx_len;
    uint8_t  pending_ack;
    uint8_t  dup_ack_count;
    uint8_t  state;
} TcpDebugSnapshot;

int32_t tcp_debug_snapshot(const TcpStreamHandle* handle,
                           TcpDebugSnapshot* out);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* TCP_SANS_IO_H */
